spring.application.name=city-problem-reporting
spring.datasource.url=jdbc:postgresql://localhost:5432/CityReportApp
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
