spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.tmgfslbgfmjeebnbbcbp
spring.datasource.password=iktAppPostgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
server.port=${SERVER_PORT:8081}

openrouter.api.key=
openrouter.model=openrouter/free

upload.dir=uploads
upload.base-url=http://192.168.1.28:8081/uploads