spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.tmgfslbgfmjeebnbbcbp
spring.datasource.password=iktAppPostgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=${SERVER_PORT:8081}


openrouter.api.key=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
openrouter.model=openrouter/free

upload.dir=uploads
upload.base-url=http://localhost:8080/uploads
openrouter.api.key=""
openrouter.model=openrouter/free
